version: '3.3'

services:
  socat:
    image: alpine/socat
    container_name: socat_proxy
    restart: always
    networks:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:2376:2375 
    command: "tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock"

  jenkins:
    build: .
    image: myjenkins-blueocean:latest
    container_name: jenkins-blueocean
    ports:
      - "58080:8080" # Host:Container
      - "50000:50000" # Host:Controller for communications betw Jenkins and Agents
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

volumes:
  jenkins-data:
  jenkins-docker-certs:

networks:
  jenkins:


# docker run --name jenkins-blueocean --restart=on-failure --detach \
#   --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
#   --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 \
#   --publish 58080:8080 --publish 50000:50000 \
#   --volume jenkins-data:/var/jenkins_home \
#   --volume jenkins-docker-certs:/certs/client:ro \
#   myjenkins-blueocean:latest

# docker run -d 
#   --restart=always 
#   -p 127.0.0.1:2376:2375 
#   --network jenkins 
#   -v /var/run/docker.sock:/var/run/docker.sock 
#   alpine/socat 
#   tcp-listen:2375,fork,reuseaddr 
#   unix-connect:/var/run/docker.sock

